- alert: HighCpuUsage
  expr: sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod, namespace) / sum(kube_pod_container_resource_limits_cpu_cores{container!=""}) by (pod, namespace) * 100 > 80
  for: 5m
  labels:
    severity: warning
  annotations:
    summary: "High CPU usage in pod {{ $labels.pod }}"
    description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using more than 80% of its CPU limit for more than 5 minutes (current value: {{ $value | humanizePercentage }})"
    runbook_url: "https://your-wiki-url/runbooks/high-cpu-usage"

- alert: NodeCpuHigh
  expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (node) * 100) > 85
  for: 10m
  labels:
    severity: critical
  annotations:
    summary: "High CPU usage on node {{ $labels.node }}"
    description: "Node {{ $labels.node }} has high CPU usage (current value: {{ $value | humanizePercentage }}) for more than 10 minutes"
    runbook_url: "https://your-wiki-url/runbooks/node-high-cpu"
