- alert: HighMemoryUsage
  expr: sum(container_memory_usage_bytes{container!=""}) by (pod, namespace) / sum(kube_pod_container_resource_limits_memory_bytes{container!=""}) by (pod, namespace) * 100 > 80
  for: 5m
  labels:
    severity: warning
  annotations:
    summary: "High memory usage in pod {{ $labels.pod }}"
    description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using more than 80% of its memory limit for more than 5 minutes (current value: {{ $value | humanizePercentage }})"
    runbook_url: "https://your-wiki-url/runbooks/high-memory-usage"

- alert: NodeMemoryHigh
  expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
  for: 10m
  labels:
    severity: critical
  annotations:
    summary: "High memory usage on node {{ $labels.node }}"
    description: "Node {{ $labels.node }} has high memory usage (current value: {{ $value | humanizePercentage }}) for more than 10 minutes"
    runbook_url: "https://your-wiki-url/runbooks/node-high-memory"
